// date localization for locale 'dk'
// generated by JÃ¶rn Zaefferer using Java's java.util.SimpleDateFormat
Date.dayNames = ['mandag', 'tirsdag', 'onsdag', 'torsdag', 'fredag', 'lørdag', 'søndag'];
Date.abbrDayNames = ['man.', 'tir.', 'ons.', 'tors.', 'fre.', 'lør.', 'søn.'];
Date.monthNames = ['januar', 'februar', 'marts', 'april', 'maj', 'juni', 'juli', 'august', 'september', 'oktober', 'november', 'december'];
Date.abbrMonthNames = ['jan.', 'feb.', 'marts', 'apr.', 'maj', 'jun.', 'jul.', 'aug.', 'sept.', 'okt.', 'nov.', 'dec.'];
